[package]
name = "bad_delaunay_apple"
version = "0.1.0"
edition = "2021"

[dependencies]
bmp = "0.5.0"
pathfinding = "4.9.1"
rmp-serde = "1.3.0"
serde = { version = "1.0.203", features = ["derive"] }
